drop table if exists event_evaluate, compilation_event_relation, compilations, requests, events, category, users;


CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL UNIQUE,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    rating     float        null
);

CREATE TABLE IF NOT EXISTS category
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP   NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

create table if not exists location
(
    id  bigint generated by default as identity primary key,
    lat float null,
    lon float null
);

CREATE TABLE IF NOT EXISTS events
(
    id                 bigint generated by default as identity primary key,
    annotation         varchar(2000) not null,
    category_id        bigint        null,
    created_at         timestamp     not null,
    description        varchar(7000) not null,
    event_date         timestamp     not null,
    initiator_id       bigint        not null,
    location_id        int           null,
    paid               boolean       not null default false,
    participant_limit  int           null,
    published_date     timestamp     null,
    request_moderation boolean       not null default true,
    state              varchar(60)   not null,
    title              varchar(120)  not null,
    views              int           null,
    count_like         int           null,
    count_dislike      int           null,
    rating             float         null
);



alter table events
    add foreign key (category_id) references category (id);
alter table events
    add foreign key (initiator_id) references users (id);
alter table events
    add foreign key (location_id) references location (id);

create table if not exists requests
(
    id           bigint generated by default as identity primary key,
    created_at   timestamp   not null,
    event_id     bigint      not null,
    requester_id bigint      not null,
    status       varchar(60) not null
);

alter table requests
    add foreign key (event_id) references events (id);
alter table requests
    add foreign key (requester_id) references users (id);

create table if not exists compilations
(
    id         bigint generated by default as identity primary key,
    pinned     boolean     not null,
    title      varchar(50) not null,
    created_at TIMESTAMP   NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

create table if not exists compilation_event_relation
(
    id             bigint generated by default as identity primary key,
    compilation_id bigint    not null,
    event_id       bigint    not null,
    created_at     TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

alter table compilation_event_relation
    add foreign key (compilation_id) references compilations (id);
alter table compilation_event_relation
    add foreign key (event_id) references events (id);

create table if not exists event_evaluate
(
    id            bigint generated by default as identity primary key,
    user_id       bigint      not null,
    event_id      bigint      not null,
    evaluate_type varchar(30) not null,
    created_at    TIMESTAMP   NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

alter table event_evaluate
    add foreign key (user_id) references users (id);
alter table event_evaluate
    add foreign key (event_id) references users (id);