version: '3.1'
services:

  stats-server:
    build: ./stats-service/stats-server
    container_name: stats-server
    hostname: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_HOTS=db
      - DB_PORT=5432
      - DB_NAME=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SERVER_PORT=9090

  main-server:
    build: ./main-service
    container_name: main-server
    hostname: main-server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOTS=db
      - DB_PORT=5432
      - DB_NAME=main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SERVER_PORT=8080
      - SERVER_STATS_URL=http://stats-server:9090

  db:
    image: postgres:13.7-alpine
    container_name: db
    hostname: db
    volumes:
      - /var/lib/postgresql/data/
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root