DROP TABLE IF EXISTS endpoint_hit;
CREATE TABLE IF NOT EXISTS endpoint_hit (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
                                            app VARCHAR(255) NOT NULL,
                                            uri VARCHAR(512) NOT NULL,
                                            ip VARCHAR(30) NOT NULL,
                                            date_hit TIMESTAMP ,
                                            CONSTRAINT pk_endpoint_hit PRIMARY KEY (id)
);